### ISSUE TITLE
Double invoked events with name same as their classname

### ISSUE THREAD

**Issue by lulco** [thephpleague/event#100]
Hi,
I am trying to upgrade this package to version 3.0 and I got some weird results when trying to subscribe to event which name is the same like its classname.

Previously it was implemented in AbstractEvent this way:

```
public function getName()
{
    return get_class($this);
}
```

So if I set the name of my event to get_class($event) or Event::class it is invoked twice.
Is it a bug or feature?

Failing test case [here](https://github.com/thephpleague/event/pull/99)

**Comment by frankdejonge** [comment]
@lulco for my understanding, why would you use a mechanism to provide an alternative name and then not use an alternative name?

**Comment by lulco** [comment]
@frankdejonge I don't know, just because I can :) I just fall into this when I was trying to upgrade package to version 3.0 but still keep old classes Event and AbstractEvent lived (I copy them into my project in faith that upgrade will be more easy - no need to delete non existing parent from all of my events etc).

Not sure if you understand my train of thought :) If you have any additional question, I will try to answer.

**Comment by frankdejonge** [comment]
@lulco if you use class names for your events, can't you just remove the named event interface from the abstract event and remove the getName getter? The dispatcher exposes two mechanisms to signal interested parties and you use both with the same value, so I'm not surprised. It could be prevented by checking if the name is the same as the class name and then skipping invocation, but the usage you are describing is redundant and not intended, so I do not want to cater for a case that shouldn't exist in the first place. I'm all for wanting to be a lazy developer, but I'm even more for not putting in supports for situations that make no sense in my opinion.

**Comment by lulco** [comment]
Yes, probably I can and it is the way how to fix it. 

I just wanted you to know about it and (maybe) add some prevention to code or at least some notice to docs.

Anyway, thank you for your quick reply. I'll close the issue and PR.

And one more thing. Yesterday I've added this package to [rector](https://github.com/rectorphp/rector/blob/main/config/set/league-event-30.php) which could help users to upgrade faster (it should help with renaming, adding and removing classes / interfaces).

**Comment by frankdejonge** [comment]
@lulco oh nice! That looks very useful 👍 I'll close the issue and the PR. Feel free to add another PR with a link to your rector for in the readme and or docs.
