### ISSUE TITLE
Split EmitterTrait

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/event#37]
This is the second time I came across the following scenario in two weeks:

Let's say I have an object which is some sort of decorator around another object. The decorated object is either an emitter or a class implementing emitter trait. If I want to access the even emitter from the outside, I probably should use emittertrait on the decorator as well. However in this case I have to override both get and set emitter functions. Not to mention the unused emitter variable in the decorator.

So I found out the folowing:

Have a trait which has the basic implementation of the emitter interface using the getEmitter() function. The getEmitter and the setEmitter should be declared as abstract.

``` php
trait EmitterAware
{
    /* Implementation */

    abstract public function getEmitter();
    abstract public function setEmitter(EmitterInterface $emitter);
}
```

Have another trait which extends the previous and implement getEmitter and setEmitter. This is what EmitterTrait is now.

``` php
trait EmitterTrait
{
    use EmitterAware;

    protected $emitter;

    public function getEmitter()
    {
        return $this->emitter;
    }

    // setEmitter
}
```

What do you think? Is it overcomplication?

The point is that you are able to retrieve an emitter from your custom implementation and use the object itself like it would be an emitter itself. (Now it is only possible to store an emitter in a property)

**Comment by sagikazarmark** [comment]
Great. :+1: 

However it seems to be different than the scenario I outlined.

The point was to have a trait where you can implement a custom emitter getter/setter logic. So a trait which holds the implementation currently `EmitterTrait` does with requiring the implementation of getter/setter methods in the class using it. And another trait which uses the previous trait and only implements these two methods. Doesn't that make sense?

**Comment by frankdejonge** [comment]
@sagikazarmark couldn't that just be a different method then?

**Comment by sagikazarmark** [comment]
Not sure what you mean. Different from what?

The point is that you are able to use the EmitterTrait logic while you can still get your emitter from a custom source (for example a decorated object) without having an unused emitter property in your object.

**Comment by frankdejonge** [comment]
@sagikazarmark could je be a little more concrete? It's a little vague now.

**Comment by sagikazarmark** [comment]
Yeah, sorry.

``` php
trait EmitterAware {
    abstract public function getEmitter();
    abstract public function setEmitter(EmitterInterface $emitter);

    public function addListener(...)
    {
        // ...
    }

    // Implementation of other emitter functions
}
```

``` php
trait EmitterTrait
{
    use EmitterAware;

    protected $emitter;

    // Implementing the emitter getter here
    public function getEmitter()
    {
        return $this->emitter;
    }

    // setEmitter
}
```

This way you can use it in a decorator like this:

``` php
class Decorator
{
    use EmitterAware;

    // holding an emitter
    protected $decorated;

    public function getEmitter()
    {
        return $this->decorated->getEmitter();
    }

    // setEmitter
}
```

Hope it's clear now ;)

**Comment by frankdejonge** [comment]
@sagikazarmark ah I see. The naming confused me. This seems more like the other part of the EmitterTrait can be exposed as a EmittingTrait.

**Comment by sagikazarmark** [comment]
Yeah, the name isn't the best.
