### ISSUE TITLE
Namespaced events?

### ISSUE THREAD

**Issue by vkbansal** [thephpleague/event#39]
Is this possible?
```php
<?php
use League\Event\Event;

$emitter->addListener('string.event.name', function (Event $event) {
    echo $event->getName(); // echo's "string.event.name"
});

$emitter->emit('string.event.*');
```

**Comment by sagikazarmark** [comment]
You can give your events any name you want. But it won't work like this. This kind of behaviour (and a lot more other) would require to either implement them all in the emitter, or use a strategy pattern for event name resolution. Both would add a big overhead.

However you are free to extend/decorate the emitter with any custom logic.

**Comment by frankdejonge** [comment]
This is not possible, nor do I have plans to implement this in the future. While I have too thought this was a good idea, it doesn't promote best practises. It's like instantiating all the classes that belong in a namespace, a bit odd, even if you need all of them anyway.
