### ISSUE TITLE
Support for partial wildcard in listener

### ISSUE THREAD

**Issue by mechastorm** [thephpleague/event#43]
I was wondering if this library does support partial wildcards in event name?

I had a use case where I did the following
```php

$emitter = new Emitter();
$this->emitter->addListener('app.action.db.*', function($event, $param) {
   // Track all events that start with 'app.action.db'
});

$emitter->emit('app.action.db.write', 1);

```

When I tried this in my app, the event did not get fired, only when I listed to 'app.action.db.write' specifically, it was caught. 

It would be great if the package supported the ability to listen to a partial wildcard - at minimum listen to all events that start with "X" for example.

**Comment by chrismichaels84** [comment]
What sort of action would you want to be fired on every db event? I can see the usefulness of this, but I was wondering what real-world problem you are having now and if a workaround may be more appropriate.

**Comment by mechastorm** [comment]
Hey,

The database example is just one possible use case. 

The real world use case that I have is for application monitoring metrics. ie. In an API library, we want to track how many times an event was triggered or how long the event took.

For instance in an application, we prefix all calls relating to API library as "client.api.*". WIth that we want to record when this event was triggered with a record call to StatsD/Graphite as count. We have a separate prefix for timing ie. "client.timing.api.*". 

The current workaround I have done is to so far use the all wildcard "*" to catch ALL events being handled by the Emitter instance. I then manually decide if that event is part of that prefix and record. This method works so far but I have reservations on the performance of this, hence why I would prefer a support for partial wildcards.

**Comment by chrismichaels84** [comment]
Well, I threw together a very small patch that adds this functionality. Its on my fork at https://github.com/chrismichaels84/event/tree/chrismichaels84-wildcards. Be sure to use the wildcards branch.

I only added a few lines to src/Emmitter.php inside the `emit()` method and then added a helper (`getWildcard()`) inside AbstractEvent.

So now, the following works as expected:
```php
$emitter = new League\Event\Emitter();

// Standard listener
$emitter->addListener('app.action.db.standard', function($event, $param) {
    echo "this is the listener for app.action.db.standard";
});

$emitter->emit('app.action.db.standard', 1);

// Wildcards
$emitter->addListener('app.action.db.*', function($event, $param) {
    echo "This will fire everytime any app.action.db event is fired."
    echo "This event wildcard was: " . $event->getWildcard();
});

$emitter->emit('app.action.db.here', 2);
$emitter->emit('app.action.db.there', 3);
$emitter->emit('app.action.db.everywhere', 4);
```

I haven't wrote any tests yet, but this doesn't break any existing tests. Lemme know if you have any feedback.

**Comment by frankdejonge** [comment]
This is something I don't have planned for this package, nor see fit in the future. It's very inexpensive to register a listener to multiple events. Since there are already `*` listeners it could be handled within the listener anyway.
