### ISSUE TITLE
Event with same priority are fired in reverse order

### ISSUE THREAD

**Issue by Anahkiasen** [thephpleague/event#44]
Consider the following code:

```php
$emitter = new Emitter();

$emitter->addListener('foobar', function () {
   echo 'a';
}, 50);

$emitter->addListener('foobar', function () {
    echo 'b';
}, 0);

$emitter->addListener('foobar', function () {
    echo 'c';
}, 0);

$emitter->addListener('foobar', function () {
   echo  'd';
}, -50);

$emitter->emit('foobar');
```

Now, as C was registered after B, I would expect it to fire after B too, but currently instead of `abcd` I get `acbd`. Is this expected behaviour? Is there any way to avoid this?

**Comment by dstockto** [comment]
I've opened a PR #45 which adds a new sort function that is stable. The emitter is using usort which is not stable so the order of elements that are deemed equivalent by the comparison function is not guaranteed to remain the same as in the original array. PR #45 should fix that and you'll get abcd.

**Comment by frankdejonge** [comment]
Closing, explanation is here: https://github.com/thephpleague/event/pull/45

**Comment by frankdejonge** [comment]
I've come back to this and ensured events are now emitted in order while respecting priority. Consider this fixed.

**Comment by Anahkiasen** [comment]
Nice, thanks!
