### ISSUE TITLE
EmitBatch with warnings or exceptions

### ISSUE THREAD

**Issue by patrickheeney** [thephpleague/event#52]
I am having some issues due to [this line](https://github.com/thephpleague/event/blob/master/src/Emitter.php#L189) when throwing exceptions within the listeners. It currently returns `array_map(): An error occurred while invoking the map callback` because the callback failed to complete, thus suppressing the original error. Would you consider switching to a `foreach` so that the errors can be caught and easily debugged?

**Comment by frankdejonge** [comment]
@patrickheeney I've tagged 2.1.1 with this fix.
