### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by NigelGreenway** [thephpleague/event#53]
Hi,

Was not sure if this was the best place, but on [http://event.thephpleague.com/2.0/listeners/classes/](http://event.thephpleague.com/2.0/listeners/classes/), the class `DomainListener` implements the `ListenerInterface`, but it has the handle type hinting `AbstractEvent` instead of `EventInterface`.

**Comment by NigelGreenway** [comment]
Sorry, did not think about looking for gh-pages branch else would have submitted a PR.
On 24 Apr 2015 10:41, Frank de Jonge <notifications@github.com> wrote:Closed #53 via 87a1e10.

**Comment by frankdejonge** [comment]
@NigelGreenway no worries :)
