### ISSUE TITLE
Additional Arguments throw exception when using AbstractListener

### ISSUE THREAD

**Issue by ellier** [thephpleague/event#65]
I followed the instructions here: http://event.thephpleague.com/2.0/events/arguments/
However, the code below throws the following error because it doesn't comply with the ListenerInterface:

> Fatal error: Declaration of App\Listeners\Error::handle(League\Event\AbstractEvent $event, $param = NULL) must be compatible with League\Event\ListenerInterface::handle(League\Event\EventInterface $event) in /home/vagrant/Code/Project/app/Listeners/Error.php on line 8

```
<?php
namespace App\Listeners;

use League\Event\AbstractEvent;
use League\Event\AbstractListener;

final class Error extends AbstractListener {
    public function handle(AbstractEvent $event, $param = null)
    {
        ...
    }	
}
```

**Comment by bobmulder** [comment]
Same here... Did a PR (#66)

**Comment by WellingGuzman** [comment]
I see what's the problem I bumped into this now that I recall, the problem here is that the interface required one parameter `

**Comment by frankdejonge** [comment]
The problem here is that the first argument is wrongly typehinted, it should be the EventInterface instead of the AbstractEvent.

**Comment by WellingGuzman** [comment]
@frankdejonge using `EventInterface` will not solve the problem, I tried, the problem here is adding a second parameter which make it incompatible:

The two solution I found was the two I mentioned above.

**Comment by frankdejonge** [comment]
```php
<?php

use League\Event\AbstractEvent;
use League\Event\AbstractListener;
use League\Event\Emitter;
use League\Event\EventInterface;
use League\Event\NamedEvent;

include __DIR__ . '/vendor/autoload.php';

class Hello extends AbstractEvent
{
    /**
     * @return mixed
     */
    public function getName()
    {
        return static::class;
    }
}

class SomeListener extends AbstractListener
{
    /**
     * Handle an event.
     *
     * @param EventInterface $event
     * @param null           $argument
     */
    public function handle(EventInterface $event, $argument = null)
    {
        var_dump($argument);
    }
}

$emitter = new Emitter();
$emitter->addListener(Hello::class, new SomeListener);

foreach (range(1, 10) as $i) {
    $emitter->emit(new Hello, 'hello ' . $i);
}
```

I just did this and everything was fine. I'm confused.

**Comment by WellingGuzman** [comment]
Oh stupid me, thanks It works, I just missed the add `use League\Event\EventInterface;`. It's all good :)

Thanks, will be nice to update the documentation here: http://event.thephpleague.com/2.0/events/arguments/.

Sorry about that.

**Comment by frankdejonge** [comment]
@WellingGuzman I've added the missing import, should be live as soon as github builds the page :)
