### ISSUE TITLE
Upcoming PSR

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/event#70]
Not sure if you are aware @frankdejonge, but there is an "EventManager" discussion: https://groups.google.com/forum/#!topic/php-fig/-EJOStgxAwY

It is almost two years old, but they picked it up again. I would be happy to see you and this package involved in that one, because currently this is probably the most usable framework agnostic Event library on the market.

**Comment by frankdejonge** [comment]
It's dead now.

**Comment by sa-tasche** [comment]
Accepted: PSFR-14 Event Dispatcher
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-14-event-dispatcher.md
