### ISSUE TITLE
waitFor method

### ISSUE THREAD

**Issue by kdubuc** [thephpleague/event#71]
What about a `waitFor` method ?

I'm not sure about this, but I want to hear your thoughts. 

I build an API which use CQRS with Events (thanks to your lib). One endpoint is used to register a device. So, i launch a command inside it like this : 

``` php
$command = new Command\RegisterDevice($user->getId(), $udid, $push_token, $platform);
$bus->handle($command);
```

I want to set the response of this endpoint with the device registered. But I must wait the registration (eg the event "DeviceRegistered") to query it and return it to the consumer.

So, I imagine this :

``` php
// Command Register device

$event = $emitter->waitFor('DeviceRegistered'); // Wait for the event, and return it when it is fired by the emitter

$query = new Query\FindDeviceByUdid($event->getUdid());
$device = $bus->handle($query);

// And return a JSON representation of the device

```

What do you think ?

**Comment by frankdejonge** [comment]
@kdubuc that would be wonderful, but PHP is synchronous and single threaded. This call would block without a possibility to break out of of. So I absolutely love the idea, it's just not really doable in PHP. Alternatively you could build something that would leverage promises and ReactPHP, but it wouldn't really fit in with how league/event is built.

**Comment by kdubuc** [comment]
Yes, it's because of this it is difficult to think CQRS / Event stream with PHP.

But, actually, I have imagined the waitFor block-able. It would be bad ?

Like an infinite loop which will be break with an event.

**Comment by kdubuc** [comment]
Okay, I get it. The infinite loop should be check the currents task, async ... And that is impossible. Argh. I should find an other idea to check if an event is complete 😐

**Comment by kdubuc** [comment]
I thinking about a potential solution : if we add an event stream that can be shared between 2 threads (threads created by internal curl, or https://github.com/bernardphp/bernard, or https://secure.php.net/manual/fr/book.pthreads.php) we can handle a waitFor method. The event stream's share system could be persistent, thanks to adapters like InMemory, File, Predis etc ..

```php
use League\Event\Emitter;
use League\Event\Stream;
use League\Event\Stream\Adapter\File;

$emitter = new Emitter();

$adapter = new File('/tmp/events.tmp');
$stream = new Stream($adapter);

$emitter->setEventStream($stream);
```

The events handled by the emitter will not be stored like array, but in the event stream (InMemory Event Stream Adapter - eg array - could be provided to avoid BC).

Example : 
- Launch a command consumer in a thread which use the emitter with the shared event stream (File adapter for example) thanks to the DI.
- In another tread (where the api request lives), build command (RegisterDevice) and send it to the handler (the command will be consumed by the other thread). And call waitFor method. The waitFor check the shared EventStream (because we use the same emitter provided by the DI) and tick until the event waited fire up.

What do you think ?

**Comment by frankdejonge** [comment]
This is out of scope for this library: a filestream can be used but since that's local state it can't scale out. Therefor a different implementation would need to be provided for other stuff, but this is not a message dispatcher, it's a simple event dispatcher.
