### ISSUE TITLE
BufferedEmitter as service

### ISSUE THREAD

**Issue by tlode** [thephpleague/event#79]
Hi,

I am using `BufferedEmitter` in a middleware for the tactician CommandBus. Therefor I've registered `BufferedEmitter` as service and injected it in an `EmitBufferedEventsMiddleware`. 

This lead to looping problems, when an event handler invoked another `Command`, because `emitBufferedEvents` did not remove the events from the buffer.

Using a copied version of `BufferedEmitter`, I slightly changed `emitBufferedEvents()` by utilizing array_shift to remove the events from the buffer. 

```php
    /**
     * Emit the buffered events.
     *
     * @return array
     */
    public function emitBufferedEvents()
    {
        $result = [];
        while($event = array_shift($this->bufferedEvents)) {
            $result[] = parent::emit($event);
        }

        return $result;
    }
```

This solved my problem using `BufferedEmitter` as a service.

**Comment by hakuno** [comment]
Hi, why don't you make a PR for?
