### ISSUE TITLE
Fatal error: Uncaught Error: Class 'League\Event\Emitter' not found

### ISSUE THREAD

**Issue by ikay007** [thephpleague/event#81]
Anytime i run the code below by browser throws an error. But if i trace it using my IDE, by pressing `ctrl ` and clicking on `new Emitter`, my IDE opens the `Emitter class`. So i don't understand why my  browser doesn't seem to find the class.

```
use League\Event\Emitter;

$emitter = new Emitter;

$emitter->addListener('foo', function (Event $event) {
    echo $event->getName(); // echo's "string.event.name"
});
```
I installed it using `composer require league/event`.

**Comment by frankdejonge** [comment]
Did you install it with composer and invulde its autoloader?
