### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mbrodala** [thephpleague/event#82]
Since there have been quite a few [changes since 2.1.2](https://github.com/thephpleague/event/compare/2.1.2...master) I'd like to know if there are plans to make a new release to include these changes.

**Comment by frankdejonge** [comment]
@mbrodala good point! I'll whip up a release now.

**Comment by mbrodala** [comment]
Can you wait a minute for me to push a PR for #79?

**Comment by frankdejonge** [comment]
@mbrodala 👍

**Comment by mbrodala** [comment]
Thanks for the quick merge, looking forward to the release. :-)

**Comment by frankdejonge** [comment]
`2.2.0` has just been released.

**Comment by mbrodala** [comment]
Great, thanks!
