### ISSUE TITLE
Upgrade from 2 to 3 documentation is... incomplete...

### ISSUE THREAD

**Issue by davidsneighbour** [thephpleague/event#94]
I am trying to upgrade my events integration from 2 to 3 using the documentation at https://event.thephpleague.com/3.0/upgrade-from-2-to-3/. Following are some points that came up during this:

1. under "Callable listeners" the text looks incomplete and stops mid (start) sentence

2. EventDispatcher - class path Event is missing in the sample:

false

```
- $emitter = new League\Event\Emitter();
+ $dispatcher = new League\EventDispatcher();
```

right

```
- $emitter = new League\Event\Emitter();
+ $dispatcher = new League\Event\EventDispatcher();
```

3. `Event::named($event)` stopped existing, but is not mentioned

4. `ListenerAcceptorInterface` disappeared, but is not mentioned - what's the replacement?

5. `AbstractListenerProvider::provideListeners` seems to have been renamed to `subscribeListeners`

**Comment by frankdejonge** [comment]
Hi, I've just added some more rename docs and an example for the named events, hope this helps.
