### ISSUE TITLE
What would be proper approach to add information to an event?

### ISSUE THREAD

**Issue by davidsneighbour** [thephpleague/event#95]
How do I add individual information to an event? I recently rewrote my v2 implementation to v3 and can't seem to wrap my head around this. I have for instance a "user.logout" event that wants to send a Slack message about the specific user logging out. How do I add something on dispatch() that is handed over to the listener callback?

**Comment by davidsneighbour** [comment]
Forget that ;) I can use the object on the dispatch function obviously.

**Comment by frankdejonge** [comment]
Hi @davidsneighbour,

I was just typing an elaborate response, but I'm glad you've figured it out! I'll add some more docs on general event creation.
