### ISSUE TITLE
Stoppable Events

### ISSUE THREAD

**Issue by davidsneighbour** [thephpleague/event#96]
The way I understand the library, if I dispatch an event "bla.fasel"' that does not exist (ie. is  not listened to) it is ignored silently (at least that's what happens with a handful of my events that are not set up yet, but called). Is there any way to remove an already set up event listener so that calling it will not result in it to be handled at all? I think the PSR calls this "[Stoppable Events](https://www.php-fig.org/psr/psr-14/#stoppable-events)". 

I found a class [StubStoppableEvent](https://github.com/thephpleague/event/blob/master/src/StubStoppableEvent.php) but I am not sure that is what I want to use ;) It looks like propagation of events is stopped. I want to remove an event that was subscribed to by `$dispatcher->subscribeTo($eventIdentifier, $listener, $priority);` by using something like `$dispatcher->unsubscribeFrom($eventIdentifier, $priority);`. Is this already possible?

**Comment by frankdejonge** [comment]
Hi @davidsneighbour,

I think you're mixing two different concepts. Let me try to explain. The StubStoppableEvent class is a test used to testing the library itself, it's not shipped in the distributed code (excluded by a `.gitattributes` export-ignore pattern). As PSR-14 requires, the event dispatching should stop calling listeners when an event is dispatched when the `isPropagationStopped` method returns `true`. This only holds true during the `$dispatcher->dispatch($event)` call. Other than adding a one-time listener, there is no way to unsubscribe a listener. A one-time listener will be automatically removed after it has been called.

Could you explain your use-case to dynamically unsubscribe a listener? Perhaps I can help you come to a different approach in the current feature-set.

**Comment by davidsneighbour** [comment]
You are right, I was mixing things up here. Let's not call them "stoppable events" ;). I was thinking about the "wordpress way" of defining action hooks (similar to events) like add_action(name, callable, priority) and them having also remove_action(name, priority) with no specific use case in mind. 

Thinking about it it seems "bad coding style" to have an event being added at one point and removed later on. My specific use case would probably be something along the lines of a login notification via various notification services (telegram, slack, sms, logfile) and later on setting services "down" that are not used by a user defined setup. But I think that is something that setup (on/off) can be done/found out when adding the event. 

So I don't really have any really applicable use-case. It's probably just bad code style if you need to "unsubscribe", don't you think?

**Comment by davidsneighbour** [comment]
The specific use-case would probably some kind of plugin-system that removes internal events to be replaced by it's own procedures. (remove, replace). For instance, my site offers a subscription email. And a plugin extends that email with more information/content.

**Comment by frankdejonge** [comment]
I think in general it's not super good practice. If anything a listener can always internally decide not to act on a message if it has reached a particular internal state and ignore subsequent messages.

**Comment by davidsneighbour** [comment]
Yeah, let's close this. Let's not open up potential new holes. Specifically with this events library I learned that looking into it for a bit longer often solves issues that are not really present. There is a reason why PSR14 does not have some kind of "remove events" functionality.
