### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by timledlie** [thephpleague/event#98]
I'm seeing two problems in the documentation:

1. https://event.thephpleague.com/3.0/upgrade-from-2-to-3/ -> PSR-14 support -> Callable listeners: "PSR-14 defines listeners as any callable. The listener interface" -- this seems to be a truncated sentence.

2. https://event.thephpleague.com/3.0/usage/subscribing-to-events/ in the first code example:
```
$dispatcher = new EventDispatcher($listenerProvider);
```
should be
```
$dispatcher = new EventDispatcher($listenerRegistry);
```

**Comment by jmauerhan** [comment]
I came to make this same report about the truncated sentence, I believe there are some instructions missing.
